changelog: 
  categories:
    - title: Breaking Changes
      labels:
        - BREAKING CHANGE
        
    - title: Novidades 🎉
      labels:
        - enhancement
        
    - title: Correções de bugs
      labels:
        - bug
        
    - title: Outras mudanças
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
        
    - title: Dependências
      labels:
        - dependencies
