name: docs

on:
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    - run: npm install vitepress sass && npm run docs:build

    - uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs/.vitepress/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}