name: Release

on:
  release:
    types: [published]
  label:
    types: [created, deleted]
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-to-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Atualização da versão do Ares
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - run: npm install @octokit/core
    - run: |
        git checkout -b update-to-latest
    - run: node scripts/latest.mjs
    - run: |
        git config user.name ${{ github.actor }}
        git add ./docs
        git commit -m "chore: atualiza versão do Ares"
        git push origin update-to-latest 
    - run: 'gh pr create -f -t "chore: atualiza versão do Ares" -H update-to-latest -B master -l auto'